"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Creation_1 = require("./Creation");
//let a = new OfPoc();
//let a = new doPoc();
//let a = new SwithMapPoc();
//let a = new MergeMapPoc();
//let a = new MapPoc();
//let a = new ConcatMapPoc();
//let a = new ConcatPoc();
//let a = new ForkJoinPoc();
//let a = new CombineLatestPoc();
//let a = new PairwisePoc();
//let a = new MergePoc();
//let a = new StartWithPoc();
//let a = new WithLatestFromPoc()
//let a = new FromPoc()
//let a = new FromPromisePoc()
//let a = new Poc()
//let a = new SetPoc()
//let a = new QueuePoc()
//let a = new DictionaryPoc()
//let a = new CatchPoc();
//let a = new RetryPoc();
//let a = new RetryWhenPoc();
//let a = new DebounceTimePoc();
//let a = new RxjsDistinctUntilChangedPoc();
//let a = new FilterPoc();
//let a = new TakePoc();
//let a = new TakeUntilPoc();
//let a = new SharePoc();
//let a = new BufferTimePoc();
//let a = new ScanPoc();
//let a = new CreatePoc();
//let a = new EmptyPoc();
//let a = new IntervalPoc();
//let a = new RangePoc();
//let a = new ThrowPoc();
let a = new Creation_1.TimerPoc();
a.test();
//# sourceMappingURL=app.js.map